name: my dotnet project 1
on:
  push:
    branches:
      - devops
jobs:
  dotnet-publish:
    runs-on: 'self-hosted'
    steps:
      - name: code checkout
        uses: actions/checkout@v5
      - name: This is my dotnet project
        run: dotnet publish  -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
        