name: mydotnet project-1

on:
  push:
    branches:
      - develop

jobs:
  myjob:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: dotnet version
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: "9.0.100"
    - name: this is my dotnet publish command
      run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=divyarekulapally_nopCommerce
          -Dsonar.organization=divyarekulapally
          -Dsonar.host.url=https://sonarcloud.io