name: my dotnet project 1
on:
  push:
    branches:
      - develop
jobs:
  dotnet-publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: sonarcloud scan
        uses: SonarSource/sonarqube-scan-action@v6
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: This is my dotnet project
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.100"
      - name: dotnet publish
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
        